# Generated by Django 3.2.9 on 2022-01-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(db_index=True, default='IT', max_length=250),
        ),
    ]
