# Generated by Django 3.2.2 on 2022-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
