# Generated by Django 3.2.2 on 2022-03-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220326_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
