# Generated by Django 3.2.2 on 2022-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='info',
            field=models.BooleanField(default=True),
        ),
    ]
