# Generated by Django 3.2.9 on 2022-01-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
