version: '3.1'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/usr/src/
    ports:
      - "8000:8000"
    env_file:
      - ./interview_quiz/.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: on-failure
volumes:
  postgres_volume: