# Generated by Django 3.2.2 on 2024-01-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
