# Generated by Django 4.0.2 on 2022-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='salary_max',
            new_name='max',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='salary_min',
            new_name='min',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='salary',
            field=models.CharField(default='', max_length=80),
        ),
    ]
